version: '3.8'

services:
  taskmanager:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

    networks:
      - taskmanager_network


networks:
  taskmanager_network:
    driver: bridge
